/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-11-30 10:14:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Date;
import com.ucc.dc.models.Task;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" $(document).ready(function() {\r\n");
      out.write("        $(\".add-row\").click(function(){\r\n");
      out.write("        debugger;\r\n");
      out.write("            var name = $(\"#name\").val();\r\n");
      out.write("            var deadline = $(\"#deadline\").val();\r\n");
      out.write("            var markup = \"<tr><td></td><td>\" + name + \"</td><td>\" + deadline + \"</td></tr>\";\r\n");
      out.write("            $(\"table tbody\").append(markup);\r\n");
      out.write("        });\r\n");
      out.write("        });\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Data Center Incoming Task and Processing</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"form-style-10\">\r\n");
      out.write("<h1>Data Center Incoming Task and Processing</span></h1>\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/InsertTask\" method=\"post\">\r\n");
      out.write("    <div class=\"section\"><span>1</span>Incoming Task Details</div>\r\n");
      out.write("    <div class=\"inner-wrap\">\r\n");
      out.write("        <label   style= \"width: 225px;\">Task Name:  <input width=\"150px\" type=\"text\" id=\"name\" placeholder=\"name\" name=\"name\">\r\n");
      out.write("        <label style= \"width: 225px;\">Task Deadline:  <input width=\"150px\" type=\"text\" id=\"deadline\" placeholder=\"Deadline\" name=\"deadline\">\r\n");
      out.write("    </div>\r\n");
      out.write("<label font-size: x-large;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    padding-bottom: 39px;\r\n");
      out.write("    color: cadetblue;>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${taskAddedToQueue}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"button-section\">\r\n");
      out.write("     <input type=\"submit\" name=\"Add Task\" />\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/InsertTask\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"button-section\" style=\"    padding-top: 20px;\">\r\n");
      out.write("     <input type=\"submit\" value=\"Process Task\" name=\"processingTask\" >\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<label font-size: x-large; font-weight: bold; padding-bottom: 39px; color: cadetblue;> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${processingtasklabel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" </label>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/InsertTask\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"button-section\" style=\"    padding-top: 20px;\">\r\n");
      out.write("     <input type=\"submit\" value=\"Get System Status\" name=\"getHvacStatus\" >\r\n");
      out.write("</div>\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tbody>\r\n");
      out.write(" <tr>\r\n");
      out.write("    <td>TASK NAME</td>\r\n");
      out.write("    <td>DEADLINE</td>\r\n");
      out.write("    <td>SERVER ID</td>\r\n");
      out.write("    <td>Processed</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<label font-size: x-large; font-weight: bold; padding-bottom: 39px; color: cadetblue;>Current HVAC Status<label>\r\n");
      out.write("<table>\r\n");
      out.write("<tbody>\r\n");
      out.write(" <tr>\r\n");
      out.write("    <td>HVAC ID</td>\r\n");
      out.write("    <td>HVAC STATUS</td>\r\n");
      out.write("    <td>STACK ID</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("table {\r\n");
      out.write("    font-family: arial, sans-serif;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td, th {\r\n");
      out.write("    border: 1px solid #dddddd;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even) {\r\n");
      out.write("    background-color: #dddddd;\r\n");
      out.write("}\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".form-style-10{\r\n");
      out.write("\twidth:450px;\r\n");
      out.write("\tpadding:30px;\r\n");
      out.write("\tmargin:40px auto;\r\n");
      out.write("\tbackground: #FFF;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\t-webkit-border-radius:10px;\r\n");
      out.write("\t-moz-border-radius: 10px;\r\n");
      out.write("\tbox-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);\r\n");
      out.write("\t-moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);\r\n");
      out.write("\t-webkit-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.13);\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 .inner-wrap{\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tbackground: #F8F8F8;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 h1{\r\n");
      out.write("\tbackground: #2A88AD;\r\n");
      out.write("\tpadding: 20px 30px 15px 30px;\r\n");
      out.write("\tmargin: -30px -30px 30px -30px;\r\n");
      out.write("\tborder-radius: 10px 10px 0 0;\r\n");
      out.write("\t-webkit-border-radius: 10px 10px 0 0;\r\n");
      out.write("\t-moz-border-radius: 10px 10px 0 0;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);\r\n");
      out.write("\tfont: normal 30px 'Bitter', serif;\r\n");
      out.write("\t-moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("\t-webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("\tbox-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("\tborder: 1px solid #257C9E;\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 h1 > span{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-top: 2px;\r\n");
      out.write("\tfont: 13px Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 label{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfont: 21px Arial, Helvetica, sans-serif;\r\n");
      out.write("\tcolor: #888;\r\n");
      out.write("\tmargin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 input[type=\"text\"],\r\n");
      out.write(".form-style-10 textarea,\r\n");
      out.write(".form-style-10 select {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\t-webkit-box-sizing: border-box;\r\n");
      out.write("\t-moz-box-sizing: border-box;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("\t-webkit-border-radius:6px;\r\n");
      out.write("\t-moz-border-radius:6px;\r\n");
      out.write("\tborder: 2px solid #fff;\r\n");
      out.write("\tbox-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);\r\n");
      out.write("\t-moz-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);\r\n");
      out.write("\t-webkit-box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.33);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-style-10 .section{\r\n");
      out.write("\tfont: normal 20px 'Bitter', serif;\r\n");
      out.write("\tcolor: #2A88AD;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 .section span {\r\n");
      out.write("\tbackground: #2A88AD;\r\n");
      out.write("\tpadding: 5px 10px 5px 10px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\t-webkit-border-radius: 50%;\r\n");
      out.write("\t-moz-border-radius: 50%;\r\n");
      out.write("\tborder: 4px solid #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin-left: -45px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tmargin-top: -3px;\r\n");
      out.write("}\r\n");
      out.write(" input[type=\"button\"], \r\n");
      out.write(" input[type=\"submit\"]{\r\n");
      out.write("\tbackground: #2A88AD;\r\n");
      out.write("\tpadding: 8px 20px 8px 20px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\t-webkit-border-radius: 5px;\r\n");
      out.write("\t-moz-border-radius: 5px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-shadow: 1px 1px 3px rgba(0, 0, 0, 0.12);\r\n");
      out.write("\tfont: normal 30px 'Bitter', serif;\r\n");
      out.write("\t-moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("\t-webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("\tbox-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.17);\r\n");
      out.write("\tborder: 1px solid #257C9E;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".form-style-10 input[type=\"button\"]:hover, \r\n");
      out.write(".form-style-10 input[type=\"submit\"]:hover{\r\n");
      out.write("\tbackground: #2A6881;\r\n");
      out.write("\t-moz-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);\r\n");
      out.write("\t-webkit-box-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);\r\n");
      out.write("\tbox-shadow: inset 0px 2px 2px 0px rgba(255, 255, 255, 0.28);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /index.jsp(71,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(71,2) '${processedTasks}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${processedTasks}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /index.jsp(71,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("processedTask");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <tr>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${processedTask.taskName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${processedTask.deadline}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${processedTask.serverId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${processedTask.processed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    </tr>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /index.jsp(93,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(93,2) '${hvacStatus}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${hvacStatus}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /index.jsp(93,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("hvac");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <tr>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hvac.hvacId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hvac.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hvac.stackId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("    </tr>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
